services:
  # api:
  #   container_name: api
  #   build: 
  #     context: .
  #     target: local
  #   volumes:
  #     - ./:/app
  #   ports:
  #     - "8080:8080"
    # command: CompileDaemon --build="go build cmd/main.go" --command=./main
  db:
    image: postgres:15.1
    restart: always
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_DB: 'TestApi'
      POSTGRES_USER: 'Me'
      POSTGRES_PASSWORD: 'Me'
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d
    # networks:
    #   - local