env: "local"
config_path: "local"
http_server:
  host: "0.0.0.0"
  port: "8080"
  timeout: 4s
  idle_timeout: 60s
db:
    dbName: "TestApi"
    dbUser: "Me"
    dbPass: "Me"
    dbHost: "localhost"
    dbPort: 5432
