env: "local"
config_path: "local"
storage_path: "./storage/storage.db"
http_server:
  host: "localhost"
  port: "8080"
  timeout: 4s
  idle_timeout: 60s
db:
    dbName: "TestApi"
    dbUser: "Me"
    dbPass: "Me"
    dbHost: "localhost"
    dbPort: 5432
